import 'package:markdown/markdown.dart' as md;

import 'code_highlighter.dart';
import 'page.dart';

// Matches h2-h6 headings that have an id attribute (generated by gitHubWeb).
// Group 1: heading level (2-6), Group 2: id value, Group 3: inner HTML.
final _headingPattern = RegExp(r'<h([2-6])\s[^>]*id="([^"]*)"[^>]*>(.*?)</h\1>', dotAll: true);

// Matches all HTML tags for stripping.
final _htmlTagPattern = RegExp(r'<[^>]+>');

// Matches the first paragraph in rendered HTML.
final _firstParagraphPattern = RegExp(r'<p>(.*?)</p>', dotAll: true);

/// Renders a page's raw Markdown content to HTML, extracting a summary and
/// table of contents.
///
/// Uses the `gitHubWeb` extension set from `package:markdown`, which includes
/// header IDs, tables, task lists, footnotes, GitHub-style alerts, strikethrough,
/// emoji, and autolinks.
///
/// Call [render] after [FrontMatterParser.parse] has populated [Page.rawContent]
/// and [Page.frontMatter].
class MarkdownRenderer {
  /// Maximum character length for auto-generated summaries.
  ///
  /// When set, summaries extracted from the first paragraph are truncated to
  /// this length on a word boundary and an ellipsis is appended. Front matter
  /// `summary` values are never truncated. `null` disables truncation.
  final int? maxSummaryLength;

  /// Build-time syntax highlighter applied to rendered code blocks, or `null`
  /// when highlighting is disabled (`highlight.enabled: false`).
  final CodeHighlighter? highlighter;

  /// Creates a [MarkdownRenderer].
  const MarkdownRenderer({this.maxSummaryLength, this.highlighter});

  /// Renders [page.rawContent] to HTML, populating:
  /// - [Page.content] — rendered HTML
  /// - [Page.summary] — front matter `summary` field if present, otherwise first
  ///   paragraph of rendered content (optionally truncated by [maxSummaryLength])
  /// - [Page.toc] — table of contents entries for h2-h6 headings
  ///
  /// If [page.rawContent] is empty, all fields remain empty/empty-list.
  void render(Page page) {
    if (page.rawContent.isEmpty) return;

    var html = md.markdownToHtml(page.rawContent, extensionSet: md.ExtensionSet.gitHubWeb);
    // Build-time syntax highlighting (ADR-010): color fenced code before it is
    // stored, so themes ship no highlighter JS. No-op when disabled.
    if (highlighter != null) html = highlighter!.highlightHtml(html);

    page.content = html;
    page.toc = _extractToc(html);
    page.summary = _resolveSummary(html, page.frontMatter, maxSummaryLength);
  }
}

/// Extracts table of contents entries from rendered HTML.
///
/// Returns a [TocEntry] for each h2-h6 element with an `id` attribute,
/// in document order. H1 headings are excluded.
List<TocEntry> _extractToc(String html) {
  return [
    for (final match in _headingPattern.allMatches(html))
      TocEntry(id: match.group(2)!, text: _stripHtml(match.group(3)!), level: int.parse(match.group(1)!)),
  ];
}

/// Resolves the page summary.
///
/// Uses [frontMatter]'s `summary` field if it is a non-empty [String],
/// otherwise falls back to the first paragraph of [html], optionally
/// truncated to [maxLength] characters on a word boundary.
String _resolveSummary(String html, Map<String, dynamic> frontMatter, int? maxLength) {
  final fmSummary = frontMatter['summary'];
  if (fmSummary is String && fmSummary.isNotEmpty) return fmSummary;
  final paragraph = _extractFirstParagraph(html);
  if (maxLength == null || maxLength <= 0) return paragraph;
  return _truncateText(paragraph, maxLength);
}

/// Truncates [html] to [maxLength] characters on a word boundary.
///
/// Strips HTML tags first, then truncates at the last space before [maxLength].
/// Appends an ellipsis (U+2026) when truncation occurs.
String _truncateText(String html, int maxLength) {
  final text = _stripHtml(html);
  if (text.length <= maxLength) return text;
  final truncated = text.substring(0, maxLength);
  final lastSpace = truncated.lastIndexOf(' ');
  if (lastSpace > maxLength ~/ 2) {
    return '${truncated.substring(0, lastSpace)}\u2026';
  }
  return '$truncated\u2026';
}

/// Extracts the inner HTML of the first `<p>` element in [html].
///
/// Returns an empty string if no paragraph is found.
String _extractFirstParagraph(String html) {
  final match = _firstParagraphPattern.firstMatch(html);
  return match?.group(1) ?? '';
}

/// Strips all HTML tags from [html], returning plain text.
String _stripHtml(String html) => html.replaceAll(_htmlTagPattern, '');
