import 'package:markdown/markdown.dart' as md;

import 'page.dart';

// Matches h2-h6 headings that have an id attribute (generated by gitHubWeb).
// Group 1: heading level (2-6), Group 2: id value, Group 3: inner HTML.
final _headingPattern = RegExp(r'<h([2-6])\s[^>]*id="([^"]*)"[^>]*>(.*?)</h\1>', dotAll: true);

// Matches all HTML tags for stripping.
final _htmlTagPattern = RegExp(r'<[^>]+>');

// Matches the first paragraph in rendered HTML.
final _firstParagraphPattern = RegExp(r'<p>(.*?)</p>', dotAll: true);

/// Renders a page's raw Markdown content to HTML, extracting a summary and
/// table of contents.
///
/// Uses the `gitHubWeb` extension set from `package:markdown`, which includes
/// header IDs, tables, task lists, footnotes, GitHub-style alerts, strikethrough,
/// emoji, and autolinks.
///
/// Call [render] after [FrontMatterParser.parse] has populated [Page.rawContent]
/// and [Page.frontMatter].
class MarkdownRenderer {
  /// Creates a [MarkdownRenderer].
  const MarkdownRenderer();

  /// Renders [page.rawContent] to HTML, populating:
  /// - [Page.content] — rendered HTML
  /// - [Page.summary] — front matter `summary` field if present, otherwise first
  ///   paragraph of rendered content
  /// - [Page.toc] — table of contents entries for h2-h6 headings
  ///
  /// If [page.rawContent] is empty, all fields remain empty/empty-list.
  void render(Page page) {
    if (page.rawContent.isEmpty) return;

    final html = md.markdownToHtml(page.rawContent, extensionSet: md.ExtensionSet.gitHubWeb);

    page.content = html;
    page.toc = _extractToc(html);
    page.summary = _resolveSummary(html, page.frontMatter);
  }
}

/// Extracts table of contents entries from rendered HTML.
///
/// Returns a [TocEntry] for each h2-h6 element with an `id` attribute,
/// in document order. H1 headings are excluded.
List<TocEntry> _extractToc(String html) {
  return [
    for (final match in _headingPattern.allMatches(html))
      TocEntry(id: match.group(2)!, text: _stripHtml(match.group(3)!), level: int.parse(match.group(1)!)),
  ];
}

/// Resolves the page summary.
///
/// Uses [frontMatter]'s `summary` field if it is a non-empty [String],
/// otherwise falls back to the first paragraph of [html].
String _resolveSummary(String html, Map<String, dynamic> frontMatter) {
  final fmSummary = frontMatter['summary'];
  if (fmSummary is String && fmSummary.isNotEmpty) return fmSummary;
  return _extractFirstParagraph(html);
}

/// Extracts the inner HTML of the first `<p>` element in [html].
///
/// Returns an empty string if no paragraph is found.
String _extractFirstParagraph(String html) {
  final match = _firstParagraphPattern.firstMatch(html);
  return match?.group(1) ?? '';
}

/// Strips all HTML tags from [html], returning plain text.
String _stripHtml(String html) => html.replaceAll(_htmlTagPattern, '');
