import 'dart:io';

import 'package:path/path.dart' as p;

/// The skin mode for a theme.
enum SkinMode {
  /// Light skin only — loads `_skins/_light.scss`.
  light,

  /// Dark skin only — loads `_skins/_dark.scss`.
  dark,

  /// Auto skin — loads both skins with `@media (prefers-color-scheme: ...)`.
  auto;

  /// Parses a skin mode from a string value.
  ///
  /// Throws [ArgumentError] if [value] is not a recognized skin name.
  static SkinMode parse(String value) {
    return switch (value) {
      'light' => SkinMode.light,
      'dark' => SkinMode.dark,
      'auto' => SkinMode.auto,
      _ => throw ArgumentError("Unknown skin '$value'. Available: light, dark, auto"),
    };
  }
}

/// Build configuration generated by the theme SASS bridge.
///
/// Holds the paths to generated SASS files and the load paths needed
/// by the SASS compiler. Consumed by `trellis_cli`'s `BuildCommand`.
class ThemeBuildConfig {
  /// The directory containing generated SASS files (`.trellis/build/`).
  final String buildDir;

  /// SASS load paths in priority order: `[.trellis/build/, site/sass/, theme/sass/]`.
  final List<String> sassLoadPaths;

  /// The resolved skin mode.
  final SkinMode skinMode;

  const ThemeBuildConfig({required this.buildDir, required this.sassLoadPaths, required this.skinMode});
}

/// Generates SASS variable files and CSS custom properties from merged theme params.
///
/// Produces two files in `.trellis/build/`:
/// - `_theme_params.scss` — SASS variables with `$trellis-` prefix and `!default`
/// - `_theme_custom_props.css` — CSS custom properties with `--trellis-` prefix (plain CSS)
///
/// Also resolves skin file paths based on the `skin` param value.
class ThemeSassGenerator {
  const ThemeSassGenerator();

  /// Generates SASS bridge files and returns the build configuration.
  ///
  /// [mergedParams] — the merged theme params (from S01's `ThemeParamMerger`).
  /// [paramTypes] — maps param names to their type hints (from `ThemeManifest.params`).
  /// [siteDir] — the site root directory.
  /// [themeDir] — the active theme directory (`null` if no theme).
  ///
  /// Creates `.trellis/build/` directory and a `.trellis/.gitignore` safety net,
  /// then writes:
  /// - `_theme_params.scss` with all params as `$trellis-*: value !default;`
  /// - `_theme_custom_props.css` with non-boolean/enum/list/map params as
  ///   `:root { --trellis-*: value; }`
  ///
  /// Returns a [ThemeBuildConfig] with load paths and skin info for the SASS compiler.
  ThemeBuildConfig generate({
    required Map<String, dynamic> mergedParams,
    required Map<String, String> paramTypes,
    required String siteDir,
    String? themeDir,
  }) {
    final buildDir = p.join(siteDir, '.trellis', 'build');
    Directory(buildDir).createSync(recursive: true);

    // Create .trellis/.gitignore safety net (ignore everything in .trellis/)
    final gitignoreFile = File(p.join(siteDir, '.trellis', '.gitignore'));
    if (!gitignoreFile.existsSync()) {
      gitignoreFile.writeAsStringSync('*\n');
    }

    // 1. Generate _theme_params.scss
    final sassVars = _generateSassVariables(mergedParams, paramTypes);
    File(p.join(buildDir, '_theme_params.scss')).writeAsStringSync(sassVars);

    // 2. Resolve skin mode
    final skinValue = mergedParams['skin'] as String? ?? 'auto';
    final skinMode = SkinMode.parse(skinValue);

    // 3. Generate _theme_custom_props.css (plain CSS, copied directly to output)
    final customProps = _generateCssCustomProperties(mergedParams, paramTypes);
    File(p.join(buildDir, '_theme_custom_props.css')).writeAsStringSync(customProps);

    // 4. Build SASS load paths: [.trellis/build/, site/sass/, theme/sass/]
    // Bridge dir is first so @import "theme_params" resolves to the generated
    // file. Site SASS is before theme SASS so site-level overrides shadow
    // theme partials of the same name.
    final sassLoadPaths = <String>[buildDir, p.join(siteDir, 'sass'), if (themeDir != null) p.join(themeDir, 'sass')];

    return ThemeBuildConfig(buildDir: buildDir, sassLoadPaths: sassLoadPaths, skinMode: skinMode);
  }
}

/// Generates SASS variable declarations from merged theme params.
///
/// Each param becomes `$trellis-{name}: {value} !default;`
/// with `_` in names converted to `-` for SASS convention.
String _generateSassVariables(Map<String, dynamic> params, Map<String, String> paramTypes) {
  final buffer = StringBuffer();
  buffer.writeln('// Auto-generated by Trellis theme system — do not edit');
  buffer.writeln('// Source: merged theme params (theme defaults + site overrides)');
  buffer.writeln();

  for (final entry in params.entries) {
    final sassName = _toSassName(entry.key);
    final type = paramTypes[entry.key] ?? 'string';
    final value = _toSassValue(entry.value, type);
    buffer.writeln('\$$sassName: $value !default;');
  }

  return buffer.toString();
}

/// Converts a param name to a SASS variable name (without `$` prefix).
///
/// `primary_color` → `trellis-primary-color`
String _toSassName(String paramName) => 'trellis-${paramName.replaceAll('_', '-')}';

/// Matches a genuine CSS hex color literal (`#rgb`, `#rrggbb`, `#rrggbbaa`).
///
/// The hex fast-path must gate on this pattern, not string length: a length-only
/// check (`length == 4 || 7 || 9`) also matched interpolation-shaped values like
/// `#{9}` (length 4) and passed them through raw, so SASS evaluated them —
/// defeating the interpolation-injection defense the escaped branch provides.
final _hexColorPattern = RegExp(r'^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$');

/// Converts a param value to a SASS value string.
///
/// String values are emitted via SASS interpolation of a quoted literal —
/// `#{"<escaped>"}` — rather than as a bare quoted literal. A quoted `!default`
/// value (e.g. `"system-ui, sans-serif"`) wins over the theme's own unquoted
/// `_variables.scss` default (since the bridge partial loads first) and
/// produces invalid CSS like `font-family: "system-ui, sans-serif"`.
/// Interpolating the quoted string yields an *unquoted* SASS string — so it
/// still satisfies `!default` overriding — but its value is unquoted, matching
/// what the theme authors would have written by hand. Unlike the legacy global
/// `unquote()`, interpolation emits no `global-builtin` deprecation warning
/// (that builtin is removed in Dart Sass 3.0.0).
///
/// Values come from semi-trusted theme.yaml / site config. Every branch that
/// emits raw (unescaped) — the hex fast-path and the `color` type hint —
/// neutralizes SASS interpolation so a `#{...}` value cannot be *evaluated*
/// (silent arbitrary-expression evaluation is the surprising hazard). Structural
/// characters (`;{}`) in a value are not neutralized here: they are build-time
/// author config, not untrusted input, and a value carrying them fails the
/// compile loudly rather than silently — a broader value-validation pass is
/// tracked as tech debt (TD-011).
String _toSassValue(dynamic value, String type) {
  if (value == null) return 'null';
  if (value is bool) return value.toString();
  if (value is num) return value.toString();
  if (value is String) {
    // Genuine hex colors pass through unquoted (matched by pattern, not length,
    // so interpolation-shaped values like `#{9}` don't slip through raw).
    if (_hexColorPattern.hasMatch(value)) return value;
    // Color type hint: pass named colors / rgb() / var() / etc. through
    // unquoted, but neutralize an interpolation marker so a `#{...}` value is
    // emitted literally instead of being evaluated.
    if (type == 'color') return value.contains('#{') ? '#{"${_escapeSassString(value)}"}' : value;
    return '#{"${_escapeSassString(value)}"}';
  }
  if (value is List) {
    return '(${value.map((v) => _toSassValue(v, 'string')).join(', ')})';
  }
  if (value is Map) {
    // Keys are escaped too — an unescaped `"` breaks the map literal and `#{`
    // in a key would inject interpolation (same threat as string values).
    final entries = value.entries.map(
      (e) => '"${_escapeSassString(e.key.toString())}": ${_toSassValue(e.value, 'string')}',
    );
    return '(${entries.join(', ')})';
  }
  return '#{"${_escapeSassString(value.toString())}"}';
}

/// Escapes a string for embedding inside a double-quoted SASS string literal.
///
/// Order matters:
/// - Backslashes are escaped first so a pre-existing `\"` in the input isn't
///   double-escaped into `\\"`, and so the escapes added below aren't
///   themselves re-escaped.
/// - `#{` is neutralized to `\#{` so a param value like `foo #{1+1}` is emitted
///   as literal text instead of being evaluated as a SASS interpolation
///   expression (values come from semi-trusted theme.yaml/site config; silent
///   evaluation or an unclosed `#{` breaking the build is a robustness hazard).
/// - Double quotes are escaped so they don't terminate the literal.
/// - Raw newlines/carriage returns are illegal inside a SASS string literal
///   (they abort compilation with "Expected \""); a CSS `\a` escape keeps a
///   multiline param value compiling as literal text.
String _escapeSassString(String value) => value
    .replaceAll(r'\', r'\\')
    .replaceAll(r'#{', r'\#{')
    .replaceAll('"', r'\"')
    .replaceAll('\r\n', r'\a ')
    .replaceAll('\n', r'\a ')
    .replaceAll('\r', r'\a ');

/// Generates CSS custom property declarations from merged theme params.
///
/// Boolean, enum, list, and map params are excluded:
/// - Booleans are SASS-only (used in `@if` conditionals)
/// - Enums are build-time config
/// - Lists/maps are not representable as single CSS values
///
/// Generates a single `:root { --trellis-*: ... }` block for all skin modes.
/// The dual `@media (prefers-color-scheme: ...)` blocks for auto dark mode are
/// handled by the theme's own SASS files.
String _generateCssCustomProperties(Map<String, dynamic> params, Map<String, String> paramTypes) {
  final buffer = StringBuffer();
  buffer.writeln('/* Auto-generated CSS custom properties — do not edit */');
  buffer.writeln();

  // Filter: exclude booleans, enums, lists, and maps
  final cssParams = <String, dynamic>{};
  for (final entry in params.entries) {
    final type = paramTypes[entry.key] ?? 'string';
    if (type == 'boolean') continue;
    if (type == 'enum') continue;
    if (entry.value is bool) continue;
    if (entry.value is List) continue;
    if (entry.value is Map) continue;
    cssParams[entry.key] = entry.value;
  }

  buffer.writeln(':root {');
  for (final entry in cssParams.entries) {
    final cssName = '--trellis-${entry.key.replaceAll('_', '-')}';
    final value = _toCssValue(entry.value);
    buffer.writeln('  $cssName: $value;');
  }
  buffer.writeln('}');

  return buffer.toString();
}

/// Converts a param value to a CSS custom property value string.
String _toCssValue(dynamic value) {
  if (value == null) return 'initial';
  if (value is num) return value.toString();
  return value.toString();
}
