import 'dart:io';
import 'dart:isolate';

import 'package:path/path.dart' as p;
import 'package:trellis_site/trellis_site.dart';
import 'package:test/test.dart';

late String _buildSiteDir;

void main() {
  setUpAll(() async {
    final packageUri = await Isolate.resolvePackageUri(Uri.parse('package:trellis_site/'));
    final packageRoot = p.dirname(packageUri!.toFilePath());
    _buildSiteDir = p.join(packageRoot, 'test', 'test_fixtures', 'build_site');
  });

  /// Creates a fresh output directory and returns a SiteConfig pointing at the
  /// build_site fixture but writing output to an isolated temp directory.
  SiteConfig isolatedConfig({bool withStatic = true}) {
    final outputDir = Directory.systemTemp.createTempSync('trellis_build_').path;
    addTearDown(() => Directory(outputDir).deleteSync(recursive: true));
    return SiteConfig(
      siteDir: _buildSiteDir,
      contentDir: p.join(_buildSiteDir, 'content'),
      layoutsDir: p.join(_buildSiteDir, 'layouts'),
      staticDir: withStatic ? p.join(_buildSiteDir, 'static') : p.join(_buildSiteDir, '_no_static'),
      outputDir: outputDir,
    );
  }

  /// Like [isolatedConfig] but with [baseUrl] set (for sitemap tests).
  SiteConfig isolatedConfigWithBaseUrl(String baseUrl, {bool withStatic = true}) {
    final outputDir = Directory.systemTemp.createTempSync('trellis_build_').path;
    addTearDown(() => Directory(outputDir).deleteSync(recursive: true));
    return SiteConfig(
      siteDir: _buildSiteDir,
      baseUrl: baseUrl,
      contentDir: p.join(_buildSiteDir, 'content'),
      layoutsDir: p.join(_buildSiteDir, 'layouts'),
      staticDir: withStatic ? p.join(_buildSiteDir, 'static') : p.join(_buildSiteDir, '_no_static'),
      outputDir: outputDir,
    );
  }

  group('BuildWarning', () {
    test('toString includes message', () {
      const w = BuildWarning('Something odd');
      expect(w.toString(), contains('Something odd'));
    });

    test('toString includes context when provided', () {
      const w = BuildWarning('Missing template', context: '/about/');
      expect(w.toString(), contains('/about/'));
    });
  });

  group('BuildResult', () {
    test('hasWarnings is false when no warnings', () {
      const result = BuildResult(pageCount: 1, staticFileCount: 0, elapsed: Duration.zero);
      expect(result.hasWarnings, isFalse);
    });

    test('hasWarnings is true when warnings present', () {
      const result = BuildResult(
        pageCount: 1,
        staticFileCount: 0,
        elapsed: Duration.zero,
        warnings: [BuildWarning('test warning')],
      );
      expect(result.hasWarnings, isTrue);
    });

    test('toString is informative', () {
      const result = BuildResult(pageCount: 5, staticFileCount: 3, elapsed: Duration(milliseconds: 42));
      final str = result.toString();
      expect(str, contains('5'));
      expect(str, contains('3'));
    });
  });

  group('TrellisSite.build()', () {
    test('returns BuildResult with positive elapsed', () async {
      final config = isolatedConfig();
      final site = TrellisSite(config);
      final result = await site.build();
      expect(result.elapsed.inMicroseconds, greaterThan(0));
    });

    test('builds all non-draft pages', () async {
      final config = isolatedConfig();
      final site = TrellisSite(config);
      final result = await site.build();
      // Fixture has: _index.md (home), about.md, no-sitemap.md, draft-page.md (draft),
      //              posts/_index.md (section), posts/hello-world.md — 5 non-draft
      expect(result.pageCount, equals(5));
    });

    test('generates home page at output/index.html', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'index.html')).existsSync(), isTrue);
    });

    test('generates single page at correct output path', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'about', 'index.html')).existsSync(), isTrue);
    });

    test('generates post page at correct output path', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'posts', 'hello-world', 'index.html')).existsSync(), isTrue);
    });

    test('draft page is not generated by default', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'draft-page', 'index.html')).existsSync(), isFalse);
    });

    test('draft page IS generated when includeDrafts = true', () async {
      final config = isolatedConfig();
      await TrellisSite(config, includeDrafts: true).build();
      expect(File(p.join(config.outputDir, 'draft-page', 'index.html')).existsSync(), isTrue);
    });

    test('generated HTML contains page title', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      final html = File(p.join(config.outputDir, 'about', 'index.html')).readAsStringSync();
      expect(html, contains('About'));
    });

    test('generated HTML contains rendered Markdown content', () async {
      final config = isolatedConfig();
      await TrellisSite(config).build();
      final html = File(p.join(config.outputDir, 'about', 'index.html')).readAsStringSync();
      expect(html, contains('about page'));
    });

    test('static CSS file is copied to output', () async {
      final config = isolatedConfig();
      final result = await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'style.css')).existsSync(), isTrue);
      expect(result.staticFileCount, greaterThan(0));
    });

    test('output directory is cleaned before build', () async {
      final config = isolatedConfig();

      // First build creates files
      await TrellisSite(config).build();

      // Plant a stale file
      final staleFile = File(p.join(config.outputDir, 'stale.html'))..writeAsStringSync('<html>stale</html>');

      // Second build should clean it away
      await TrellisSite(config).build();
      expect(staleFile.existsSync(), isFalse);
    });

    test('missing layouts directory throws TemplateNotFoundException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_no_layouts_');
      addTearDown(() => tempDir.deleteSync(recursive: true));

      // Site with content but no layouts
      Directory(p.join(tempDir.path, 'content')).createSync();
      File(p.join(tempDir.path, 'content', 'page.md')).writeAsStringSync('---\ntitle: Page\n---\nContent.\n');
      Directory(p.join(tempDir.path, 'layouts')).createSync(); // empty!
      final outputDir = p.join(tempDir.path, 'output');

      final config = SiteConfig(siteDir: tempDir.path, outputDir: outputDir);
      expect(TrellisSite(config).build(), throwsA(isA<TemplateNotFoundException>()));
    });

    test('build with no static directory has no copied static files (only sitemap)', () async {
      final config = isolatedConfig(withStatic: false);
      final result = await TrellisSite(config).build();
      // staticFileCount includes the sitemap (1), but no copied assets
      expect(result.staticFileCount, lessThanOrEqualTo(1));
    });

    test('BuildResult.pageCount matches non-draft page count', () async {
      final config = isolatedConfig();
      final result = await TrellisSite(config).build();
      // 5 non-draft pages: home, about, no-sitemap, posts/_index, posts/hello-world
      expect(result.pageCount, equals(5));
    });

    test('build generates sitemap.xml in output directory', () async {
      final config = isolatedConfigWithBaseUrl('https://example.com');
      await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'sitemap.xml')).existsSync(), isTrue);
    });

    test('sitemap contains non-draft pages', () async {
      final config = isolatedConfigWithBaseUrl('https://example.com');
      await TrellisSite(config).build();
      final xml = File(p.join(config.outputDir, 'sitemap.xml')).readAsStringSync();
      expect(xml, contains('https://example.com/about/'));
      expect(xml, contains('https://example.com/posts/hello-world/'));
    });

    test('sitemap excludes draft pages', () async {
      final config = isolatedConfigWithBaseUrl('https://example.com');
      await TrellisSite(config).build();
      final xml = File(p.join(config.outputDir, 'sitemap.xml')).readAsStringSync();
      expect(xml, isNot(contains('/draft-page/')));
    });

    test('sitemap excludes pages with sitemap: false front matter', () async {
      final config = isolatedConfigWithBaseUrl('https://example.com');
      await TrellisSite(config).build();
      final xml = File(p.join(config.outputDir, 'sitemap.xml')).readAsStringSync();
      expect(xml, isNot(contains('/no-sitemap/')));
    });

    test('sitemap counts as 1 static file in BuildResult', () async {
      final config = isolatedConfigWithBaseUrl('https://example.com', withStatic: false);
      final result = await TrellisSite(config).build();
      expect(result.staticFileCount, equals(1));
    });
  });

  group('TrellisSite output directory safety', () {
    test('outputDir as parent of siteDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final fakeSiteDir = p.join(tempDir.path, 'site');
      Directory(fakeSiteDir).createSync();

      final config = SiteConfig(
        siteDir: fakeSiteDir,
        outputDir: tempDir.path,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });

    test('outputDir == siteDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));

      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: tempDir.path,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });

    test('outputDir == contentDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final contentDir = p.join(tempDir.path, 'content');
      Directory(contentDir).createSync();

      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: contentDir,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });

    test('outputDir == layoutsDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final layoutsDir = p.join(tempDir.path, 'layouts');
      Directory(layoutsDir).createSync();

      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: layoutsDir,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });

    test('outputDir == staticDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final staticDir = p.join(tempDir.path, 'static');
      Directory(staticDir).createSync();

      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: staticDir,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });

    test('outputDir == dataDir throws SiteConfigException', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_safety_');
      addTearDown(() => tempDir.deleteSync(recursive: true));
      final dataDir = p.join(tempDir.path, 'data');
      Directory(dataDir).createSync();

      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: dataDir,
      );
      expect(TrellisSite(config).build(), throwsA(isA<SiteConfigException>()));
    });
  });

  group('sitemap baseUrl enforcement', () {
    test('empty baseUrl skips sitemap generation', () async {
      final config = isolatedConfig();
      final result = await TrellisSite(config).build();
      expect(File(p.join(config.outputDir, 'sitemap.xml')).existsSync(), isFalse);
      // No sitemap counted in static files
      expect(result.staticFileCount, equals(1)); // only style.css
    });
  });

  group('draft bundle asset filtering', () {
    test('draft page bundle assets are not copied to output', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_draft_bundle_');
      addTearDown(() => tempDir.deleteSync(recursive: true));

      // Set up a minimal site with a draft page bundle
      final contentDir = p.join(tempDir.path, 'content');
      final bundleDir = p.join(contentDir, 'draft-post');
      Directory(bundleDir).createSync(recursive: true);
      File(p.join(bundleDir, 'index.md')).writeAsStringSync(
        '---\ntitle: Draft\ndraft: true\n---\nDraft content.\n',
      );
      File(p.join(bundleDir, 'image.png')).writeAsBytesSync([0x89, 0x50, 0x4e, 0x47]);

      final layoutsDir = p.join(tempDir.path, 'layouts', '_default');
      Directory(layoutsDir).createSync(recursive: true);
      File(p.join(layoutsDir, 'single.html')).writeAsStringSync(
        '<html><body tl:utext="\${page.content}">content</body></html>',
      );

      final outputDir = p.join(tempDir.path, 'output');
      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: outputDir,
      );
      await TrellisSite(config).build();

      // Draft page HTML should not exist
      expect(File(p.join(outputDir, 'draft-post', 'index.html')).existsSync(), isFalse);
      // Draft bundle asset should not be copied
      expect(File(p.join(outputDir, 'draft-post', 'image.png')).existsSync(), isFalse);
    });
  });

  group('custom dataDir', () {
    test('global data loaded from custom dataDir', () async {
      final tempDir = Directory.systemTemp.createTempSync('trellis_datadir_');
      addTearDown(() => tempDir.deleteSync(recursive: true));

      // Set up site with custom data dir
      final contentDir = p.join(tempDir.path, 'content');
      Directory(contentDir).createSync();
      File(p.join(contentDir, 'page.md')).writeAsStringSync(
        '---\ntitle: Page\n---\nContent.\n',
      );

      final customDataDir = p.join(tempDir.path, 'my_data');
      Directory(customDataDir).createSync();
      File(p.join(customDataDir, 'site_info.yaml')).writeAsStringSync('company: Acme Corp');

      final layoutsDir = p.join(tempDir.path, 'layouts', '_default');
      Directory(layoutsDir).createSync(recursive: true);
      File(p.join(layoutsDir, 'single.html')).writeAsStringSync(
        '<html><body><span tl:text="\${data.site_info.company}">company</span></body></html>',
      );

      final outputDir = p.join(tempDir.path, 'output');
      final config = SiteConfig(
        siteDir: tempDir.path,
        outputDir: outputDir,
        dataDir: customDataDir,
      );
      await TrellisSite(config).build();

      final html = File(p.join(outputDir, 'page', 'index.html')).readAsStringSync();
      expect(html, contains('Acme Corp'));
    });
  });
}
